dependencies:
 - OpenZeppelin/openzeppelin-contracts@4.6.0
compiler:
 solc:
  remappings:
    - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0'
    - "OpenZeppelin=/home/anshik1998/.brownie/packages/OpenZeppelin"